print("Het is een lange, moeizame dag geweest, je hebt een glas melk opgewarmd en gaat in bed nog een beetje liggen lezen. De zon is al onder en de maan is verscholen achter donkere wolken, waardoor het enige licht in je slaapkamer afkomstig is van de kandelaar naast je hoofdeinde. Na een tijdje leg je het boek naast je neer, blaas je de kaars uit en sluit je je ogen, je vaag bewust zijnde van de regen die buiten op je raam klettert. Langzaam zak je weg en val je in een diepe slaap...Plots schrik je op van een heftige donderstoot. Je weet niet hoe laat het is, maar je ziet nog steeds geen steek, de regen is nog niet opgehouden -integendeel, het is alleen maar harder gaan regenen -en het is zelfs begonnen te onweren. Wanneer een tweede bliksemschicht je raam oplicht zie je tot je afschuw het groene hoofd van een goblin naar binnen turen. Geschokt val je uit je bed en grijp je vergeefs naar het zwaard dat op de gang en dus niet naast je bed ligt. Intussen veegt de goblin de regendruppels van het natte raam en besef je dat hij je heeft gezien. Je besluit om...")
print("A: te blijven liggen")
print("B:naar buiten te gaan")
keuze = input()
if keuze == 'A':
    print("Je kruipt snel weer je bed in, trekt je kussen over je hoofd heen en probeert de gebeurtenissen van zo-even te vergeten. Het zal maar je verbeelding zijn geweest, vast te wijten aan het overslaan van het middageten de vorige dag. Verdere bliksemschichten blijven uit, en je begint al enigszins te ontspannen, wanneer er twee korte kloppen bij je voordeur weerklinken. De kloppen blijven maar doorgaan, en je beseft dat je er toch iets aan zult moeten doen. Je...")
elif keuze =='B':
    print("De kandelaar floept op magische wijze weer aan en plots is de kamer weer prettig verlicht. Je trekt snel een leren wambuis over je nachthemd heen en doet een stevige broek aan. Vervolgens grijp je de kandelaar en loop je met stevige passen richting de voordeur. Onderweg raap je nog je zwaard op en klem je dit stevig in je rechterhand vast.Eenmaal bij de voordeur zet je de kandelaar neer en open je voorzichtig de deur op een kier, half verwachtend dat er over enkele ogenblikken een horde goblins naar binnen stormt. Er staat echter maar één goblin, helemaal verzopen en eerder lachwekkend dan angstaanjagend.Snel drukt hij een vochtige brief in je handen, waardoor je je zwaard laat vallen, om vervolgens door een gat in de heg de nacht in te verdwijnen. Je...")
    
          
